### ISSUE TITLE
Я не розумію

### ISSUE THREAD

**Issue by YaHto** [Roavello/undertale_ua#1]
А якщо машина за виробництвом самогону(Delta Patcher) видає наступну помилку:  An error has occurred: xdelta3: source file too short: XD3_INVALID_INPUT
То що робити і як змусити шайтан-машину робити те, що мені потрібно?

**Comment by Roavello** [comment]
Вітаю, YaHto.
Можете сказати яку версію гри ви використовуєте, та чи встановлювали раніше на неї якісь інші моди?

**Comment by YaHto** [comment]
1.08, Модів не встановлював

**Comment by Roavello** [comment]
В такому разі, спробуйте спочатку застосувати патч "v1.08_Windows_Collectors_Edition_to_Steam", а вже після патч з перекладом.
Якщо не допоможе, перевстановіть гру та знову спробуйте застосувати патч з перекладом.
Сподіваюся, це вам допоможе.

**Comment by YaHto** [comment]
Спробував обидва.  І перевстановлювати пробував. Не допомогло. Може ще які варіанти будуть?

**Comment by YaHto** [comment]
І ще. В мене є ідея. Коли зберетеся перекладати Водоспад, то чому б вам не зробити так, щоб Теммі, окрім Боба розмовляли на суржику?

**Comment by marklangerhacker** [comment]
> І ще. В мене є ідея. Коли зберетеся перекладати Водоспад, то чому б вам не зробити так, щоб Теммі, окрім Боба розмовляли на суржику?

Може, ти мав на увазі сленг? Якщо суржик, то ні, бо просто писати безграмотно-то не те ж саме, що писати суржиком

**Comment by YaHto** [comment]
Ну так.

**Comment by Roavello** [comment]
Бачу, що тема змістилася з проблеми на рекомендації та пропозиції.
Рекомендую перенести вашу ідею з Теммі у гілку з пропозиціями.

> An error has occurred: xdelta3: source file too short: XD3_INVALID_INPUT

Ця помилка з'являється якщо застосовувати патч перекладу на стару версію гри.
Тому впевніться, що у вас остання Steam версія гри.
Я не бачу сенсу тримати цю гілку відкритою і далі.
Дякую за співпрацю.

**Comment by agent3397** [comment]
я совесм не понимаю установить его
